gap-packages/AutoDoc

- CHANGES
- PackageInfo.g
- gap/Magic.gd
- gap/Magic.gi
- makedoc.g
- makefile
This change allows packages to get rid of `SetPackagePath(PACKAGE, ".");` in their `makedoc.g` files, which improves robustness. It is also cruicial for the new `matrices` package <https://github.com/gap-packages/matrices> which cannot use `SetPackagePath` reliably (it is a required package, so always loaded, but `SetPackagePath` is problematic for packages which are loaded).
> Allow passing directory objects (instead of package names) to AutoDoc()

- PackageInfo.g
- doc/Comments.xml
- doc/Tutorials.xml
- gap/DocumentationTree.gd
- gap/DocumentationTree.gi
- gap/Parser.gi
Some more work on the tutorials, specially for those mentioned in #101
> Preserving leading spaces in code blocks, documentation.

- CHANGES
- gap/AutoDocMainFunction.gi
Instead of "01/02/2015" this outputs "1 February 2015", which is less ambiguous.
Of course some people will prefer ""1st February 2015" or even ""February 1st, 2015". Note that the GAP function `Ordinal` would make it quite easy to implement that.
I don't want to provide an option to choose formats, though, let's just pick one (e.g. the one I now used).
> Use english month names on title pages

- gap/AutoDocMainFunction.gi
- gap/Magic.gd
Resolves #120 
The old entities code is kept for backwards compatibilit, but is intentionally left undocumented
A potential enhancement to this would be to print a warning if the entities are specifiedas a list.
> Rewrite entities support and document it

- PackageInfo.g
- doc/Comments.xml
- gap/DocumentationTree.gi
- gap/Markdown.gi
- gap/Parser.gi
- gap/ToolFunctions.gi
* Correct scanning of ´KeyDependendOperation`
* No label for functions with no filters
* No argument for functions with no argument
* Documentation of `DeclareConstructor`
* No return statement printed if no `@Returns` is given
* ChapterLabel, SectionLabel, SubsectionLabel
* Listing for GAPDoc example style
* Fixup of example doc
> Several improvements

- PackageInfo.g
- gap/Markdown.gi
Inserting `<P/>` for #! followed by an empty line
caused `<P/>` inserted in places in lists which were
not inside Item environments.
> Fixed bug in XML-Generation

- gap/DocumentationTree.gi
and do not use in-place NormalizeWhitespace in printing of string
since normalizing the string can cause markdown parser to fail the
second time a chunk is inserted. Closes #141.
> Make copy of string before printing string,

- doc/Comments.xml
- gap/Parser.gi
Since GAPDoc only highlights the examples properly if there is no space in front
of the gap> prompt, the standard is now that one character after the AutoDoc comments is
removed.
> Spacing in new @ExampleSession environment:

- doc/Comments.xml
Fixed inconsistencies in documentation:
* Documented `@BeginExampleSession` instead of `@ExampleSession`
* Documented aliases `@Example`, `@Log`, `@ExampleSession`, and `@LogSession`
> Consistent documentation

- PackageInfo.g
- gap/Magic.gi
and make it overrideable via gapdoc_latex_option
> Removed the hardcoded utf8 option

- PackageInfo.g
- gap/Parser.gi
Before this patch, filter lists
of operations and methods for operations
containing `\[\]` were not scanned correctly,
as AutoDoc assumed the filters in this operations
were between those brackets.
> Scan bracket declarations correctly

- doc/Comments.xml
- gap/Markdown.gi
- tst/worksheets/general.expected/_Chapter_SomeChapter.xml
- tst/worksheets/general.sheet/worksheet.g
And, on the way, make markdown support different markers
for beginning and end of a tag
> Added possibility to mark function arguments via {A}

- gap/AutoDocMainFunction.gi
- gap/ToolFunctions.gd
- gap/ToolFunctions.gi
- tst/AUTODOC_SetIfMissing.tst
- tst/misc.tst
- tst/worksheets/general.expected/title.xml
- tst/worksheets/general.sheet/worksheet.g
This way, other code can format dates in a "human friendly" fashion, e.g. for use in XML entities for the package date.
Perhaps something like this should instead be added to GAP itself, or the utils package, but we can start here for now.
> Add AUTODOC_FormatDate helper

- gap/Magic.gi
There are two ways to pass options to the `AutoDoc` function:
(1) Using the "options stack": `AutoDoc( package : options )`
(2) Using a second argument which is a record: `AutoDoc( package, options )`
All the options that `AutoDoc` expect can be passed in either of these
two forms, except the option `extract_examples`, which is only accepted
in form (2).  I changed this so that `extract_examples` is accepted in
both forms.
(It seems like form (1) is undocumented.  An alternative approach to
fix this inconsistency -- and avoid similar inconsistencies in the
future -- would be to remove form (1) completely.)
> Recognize extract_examples as option to AutoDoc

- doc/Comments.xml
- address parts of issue #157
- use &AutoDoc; entity in some additional spots
- replace @ExampleSession by @BeginExampleSession in the documentation
for @BeginExampleSession
- use <C>...</C> when referring to AutoDoc @-commands
- improve index entries for @-commands
- a bunch of minor typos and tweaks of the text
> Improve manual

- doc/Tutorials.xml
This fixes 2 broken references in the manual.
> Add BookName="ref" to Test and TestDirectory references.

- CHANGES
- doc/Comments.xml
- gap/Parser.gi
Specifically, add deprecation warnings for @InsertSystem, @System, @BeginSystem, @EndSystem (use @Chunk etc. instead), and also @EndSection, @EndSubsection.
These warnings are shown for info level InfoWarning >= 1, and in red color to make sure they are seen by the user.
Also, the manual was changed to document these tags as deprecated, and what to use instead.
This mostly resolves the issues #205 and #206; however, we might keep those open to remind us that one day in the future (let's say, in one year?) we could make a release were those deprecated tags are completely removed; or at least removed from the manual.
> Implicitly end subsection when a manpage starts; add deprecation warnings

- doc/Tutorials.xml
- gap/Magic.gd
- gap/Magic.gi
- makedoc.g
- tst/manual.expected/_Chapter_AutoDoc.xml
This is a first attempt to address issue #149. 
After these changes the following makedoc.g files appear to run correctly: (1) after changing to GAPDocLatexOptions - AutoDoc; XMod,  (2) still using gapdoc_latex_options: groupoids; intpic; factint; sgpviz, xmodalg.  The makedoc.g in numericalsgps throws a lot of 'inputenc Errors', but that may not be due to this PR? 
Question: should the entities also be moved from scaffold to gapdoc? 
Resolves #149
> Replace scaffold.gapdoc_latex_options by gapdoc.LaTeXOptions

- gap/Parser.gi
- tst/worksheets/general.expected/_Chapter_SomeChapter.xml
- tst/worksheets/general.sheet/worksheet.g
Note that AutoDoc here duplicates logic in `gap/lib/coll.gd` to determine the
actual name of the symbol being defined by the call (since that symbol is
computed on the fly by the declaration and does not appear verbatim anywhere
in the call). This is unfortunate, but I could not see any way to call the
relevant code in the standard library, as the name computation of the
collections category is not split out into a separately executable function.
Also, modify the `worksheet.tst` to include an example of
`DeclareCategoryCollection` to make sure the new capacity is tested.
Note that this pull request is on top of the changes made for pull request #166, because otherwise I wasn't sure how to ensure that this pull request included test for the new facility; I just needed to be on top of a …
>  Handle documentation of DeclareCategoryCollection declarations. 

- gap/Magic.gd
- tst/manual.expected/_Chapter_AutoDoc.xml
Specifically:
1. Modify the argument list to indicate that the two parameters are each
independently optional.
2. Add creating a maketest.g to the list of tasks AutoDoc() can perform.
3. Clarify that the package parameter determines both the package directory in
which AutoDoc will operate and the metadata for the package being documented,
and describe more precisely how it does so.
4. Clarify how the package directory and metadata work in the worksheet case.
5. Clarify the semantics of the dir entry in the options record.
Resolves: #163 (note this replaces a former pull request to resolve that issue which became "dirty" with additional commits).
> Repair minor omissions/imprecisions in AutoDoc() function doc

- doc/Comments.xml
- gap/DocumentationTree.gi
- gap/Parser.gi
- gap/ToolFunctions.gi
- tst/worksheets/general.expected/_Chapter_SomeChapter.xml
- tst/worksheets/general.sheet/worksheet.g
Previously, there was no way to modify the subsection heading of a @Group, but
the documentation even stated "Note that it is currently not possible to give
a header to the Group in the manual..." Hence, the addition of a @GroupTitle
command to allow exactly that.
Co-Authored-By: Max Horn <max@quendi.de>
Resolves #90 
Closes #172 (this is a modified version of that PR, which was authored by @gwhitney, with `@GroupInitialArguments` removed, a test added, some wording updated
> Add @GroupTitle command

- gap/Parser.gi
- tst/worksheets.tst
- tst/worksheets/autoplain.expected/_Chapter_Test.xml
- tst/worksheets/autoplain.sheet/plain.autodoc
- tst/worksheets/general.sheet/worksheet.g
- tst/worksheets/plain.expected/_Chapter_Test.xml
- tst/worksheets/plain.sheet/plain.g
In order to uniformize the handling of #! prefixes in AutoDoc files,
gap/Parser.gi is changed to pass lines between @BeginExampleSession and
@EndExampleSession through unchanged when plain_text_mode is true.
Note this commit also supplies two test worksheets. They will not have any
effect unless/until the test harness supplied with pull request #180 is put in
place. But the worksheets do at least serve as illustrations of the intended
behavior post this change, and should otherwise be innocuous.
Resolves #167 
This replaces pull request #168, which I will now close.
> Make @Begin.../@EndExampleSession respect plain_text_mode

- .gitignore
- gap/DocumentationTree.gi
- gap/Magic.gi
- tst/worksheets/general.expected/_Chapter_SomeChapter.xml
- tst/worksheets/general.expected/_Chunks.xml
- tst/worksheets/general.sheet/worksheet.g
Implements #217 by making `@Chunk` using `<#GAPDoc Label=...>`.
Resolves #217
> Made Chunks compatible with GAPDoc chunks

- gap/Magic.gi
Application: I have multiple .autodoc files which should be detected via
"scan_dirs". However, there is a main .autodoc file which should be
included first as it defines the order of chapters and sections. Thus, I
pass this file to "files" explicitly. This commit makes sure that it is not
included twice if I do that.
Note: Since the order is relevant I have used DuplicateFreeList instead of
Set to keep the order of the first occurrence (which I hope
DuplicateFreeList actually does).
> Remove duplicate entries in autodoc.files

- gap/AutoDocMainFunction.gi
As we see in the existing code just below the diff, AutoDoc always generates test files with at least two digits added before the `.tst`. Therefore we should check for the presence of at least two digits.
Fixes #259.
> Extract examples: do not delete `pkgname.tst`

- doc/Tutorials.xml
Changed makedoc.g to PackageInfo.g, where the names of io and PackageName are defined.
Found this error where searching how to define/use entity &lt which is not working for me.
> change referenced file

- gap/AutoDocMainFunction.gi
- gap/Magic.gd
- gap/Magic.gi
- gap/ToolFunctions.gi
- tst/dogfood.tst
- tst/manual.expected/_Chapter_AutoDoc.xml
- tst/testall.g
- tst/worksheets.tst
In various places, AutoDoc uses `Print` to print status messages, with no way to silence these.  This is a bit annoying in automated workflows like the package manager.
This PR adds a new info class `InfoAutoDoc` which is used instead of `Print`.  It's currently binary: 1 for messages and 0 for no messages.  The default is 1, of course.
> Add InfoAutoDoc for messages instead of Printing
