gap-packages/AutoDoc

- PackageInfo.g
- doc/Comments.xml
- doc/Tutorials.xml
- gap/AutoDocMainFunction.gd
- gap/AutoDocMainFunction.gi
- gap/Magic.gi
- gap/Parser.gi
Closes #95. More refactoring to come here.
Could you have a look whether this tutorial about worksheets helps to understand their functionality?
> Made worksheets work again, added a tutorial for worksheets

- PackageInfo.g
- gap/Magic.gi
> Off-by-one error in AUTODOC_GetSuffix

- PackageInfo.g
- gap/Magic.gi
Otherwise date cannot be parsed.
> Made titlepage.Date a string in worksheets

- gap/Parser.gi
- gap/ToolFunctions.gd
- gap/ToolFunctions.gi
- read.g
Scan `DeclareConstructor` and automatically put constructor ManItem.
> Declare constructor

- doc/Comments.xml
- gap/DocumentationTree.gi
- gap/Parser.gi
which differ from the names given to the chapter/section/subsection
> Added @*Title commands to specify titles for Chapters etc.

- PackageInfo.g
- doc/Comments.xml
- gap/Markdown.gi
- tst/dogfood.tst
- tst/worksheets/general.expected/_Chapter_SomeChapter.xml
- tst/worksheets/general.sheet/worksheet.g
This implements part of issue #184
> Accept single backticks to indicate inline code spans

- gap/AutoDocMainFunction.gi
We allow specifying entities in two ways:
1. as a list of pairs (legacy mode);
2. as a record mapping entity names to values.
The code handling these two variants different in how things were
quoted. This commit ensures we always use the same quoting rules for old
and new style entities specifications.
> Uniform entities handling

- .gitignore
- PackageInfo.g
- doc/Tutorials.xml
- doc/clean
This contains some minor change which were previously contained in PR #191.
> Misc changes: folder -> directory; remove refs to VERSION file; update copyright to 2019

- doc/Comments.xml
- gap/Parser.gi
- tst/worksheets/general.expected/_Chapter_SomeChapter.xml
- tst/worksheets/general.sheet/worksheet.g
Fixes #186
Note: I have no deep understanding of the parser code. I have just copied the `LatexOnly` parts and in my tests everything works.
> Provide `@NotLatex` in addition to `@LatexOnly`

- CHANGES
- PackageInfo.g
- gap/AutoDocMainFunction.gi
> Only add package authors to manual title page; add some contributors to PackageInfo.g

- CHANGES
- PackageInfo.g
@sebasguts if you are OK with doing a release right now, please merge this; I'll then run the `release` tool as necessary.
> Version 2019.05.20

- gap/DocumentationTree.gd
- gap/DocumentationTree.gi
- gap/Magic.gi
- gap/ToolFunctions.gi
... instead of (ab)using options to pass this value around.
> Make level_value an explicit arg of WriteDocumentation

- doc/Comments.xml
- doc/Tutorials.xml
> Improve manual further

- gap/DocumentationTree.gi
- tst/worksheets/general.expected/_Chapter_SomeChapter.xml
- tst/worksheets/general.expected/tst/general_test01.tst
- tst/worksheets/general.sheet/worksheet.g
> Support `]]>` in examples

- gap/Parser.gi
- tst/worksheets/general.expected/_Chapter_SomeChapter.xml
- tst/worksheets/general.sheet/worksheet.g
> Handle DeclareGlobalName and some more tests

- CHANGES
- gap/AutoDocMainFunction.gd
- gap/AutoDocMainFunction.gi
- gap/DocumentationTree.gi
- gap/Magic.gi
- gap/ToolFunctions.gd
- gap/ToolFunctions.gi
> Fix "missing _Chunks.xml" warning and some other tweaks

- CHANGES
- gap/AutoDocMainFunction.gi
> Remove outdated extracted tst files

- gap/AutoDocMainFunction.gi
... as e.g. used by Cchunks.xml
Fixes #246
> AUTODOC_ExtractMyManualExamples: support absolute paths

- gap/AutoDocMainFunction.gd
- gap/AutoDocMainFunction.gi
- gap/DocumentationTree.gi
- gap/Magic.gi
- gap/ToolFunctions.gd
- gap/ToolFunctions.gi
Also remove `AUTODOC_AbsolutePath`
> Revise handling of chunks XML file

- gap/DocumentationTree.gd
- gap/DocumentationTree.gi
- gap/Parser.gi
- tst/worksheets.tst
- tst/worksheets/general.expected/_AutoDocMainFile.xml
- tst/worksheets/general.expected/_Chapter_labelChapter.xml
- tst/worksheets/general.sheet/worksheet.g
Old branch from August 2019 sitting on my disk...
> Make Label() a mutable attribute, get rid of additional_label
